### ISSUE TITLE
connect from external client

### ISSUE THREAD

**Issue by diman82** [KEINOS/Dockerfile_of_SQLite3#36]
Is it possible to connect from an external client (e.g. DBeaver)?
If positive, is any additional configuration is required? What port should be exposed?

**Comment by KEINOS** [comment]
> Is it possible to connect from an external client (e.g. DBeaver)?

Just to confirm, do you want to edit the SQLite database in the Docker container from a locally installed DBeaver, for example?

In that case, **the easiest way is to publish/expose the DB file** from the container. This is because SQLite is not a client-server database and therefore has no ports to expose.

1. Mount the local directory in the container as a volume.
2. Run the application in a container and create a SQLite database file on the mounted volume.
3. After shutting down the container, open/edit the db file locally using DBeaver.

## Example

As a concrete example, we will create two files: a Python3 script using SQLite and docker-compose to run in a container.

```shellsession
$ tree
.
├── todo.py
└── docker-compose.yml
```

### `todo.py`

This python3 script is a very simple CLI application that can only add tasks and print task lists. There is no editing functionality.

```python3
import sqlite3

try:
    conn = sqlite3.connect("todo.db")
    print("* Opened database successfully")

    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS tasks(
            id    INTEGER PRIMARY KEY AUTOINCREMENT,
            task  STRING NOT NULL
        );
        """
    )
    print("* Table created successfully")

    while True:
        stdIn = input("Enter new task (l=list, q=quit): ")
        if stdIn == "q":
            break
        if stdIn == "l":
            cursor = conn.execute("SELECT * FROM tasks;")
            print(cursor.fetchall())
            continue

        conn.execute("INSERT INTO tasks(task) VALUES (?)", (stdIn,))
        conn.commit()

        print("* Record created successfully: " + stdIn)

    conn.close()
except sqlite3.Error as error:
    print("! Error while creating a sqlite table", error)
finally:
    if conn:
        conn.close()
        print("* sqlite connection is closed")
```

### `docker-compose.yml`

This docker compose configuration file creates a python container that mounts the current directory in `/workspaces` and executes the `todo.py` script.

```yaml
version: "3.9"

services:
  todo:
    image: python:alpine
    volumes:
      - .:/workspaces
    working_dir: /workspaces
    entrypoint: [ "/usr/local/bin/python" ]
    command: [ "todo.py" ]
    tty: true
    stdin_open: true
```

### Execute

Run `docker compose run todo`, add some tasks, enter `q` and exit.

```shellsession
$ docker compose run todo
* Opened database successfully
* Table created successfully
Enter new task (l=list, q=quit): buy milk
* Record created successfully: buy milk
Enter new task (l=list, q=quit): do 10 push-ups
* Record created successfully: do 10 push-ups
Enter new task (l=list, q=quit): l
[(1, 'buy milk'), (2, 'do 10 push-ups')]
Enter new task (l=list, q=quit): q
* sqlite connection is closed
```

Next, check that the db file has been created in the current directory.

```shellsession
$ tree
.
├── todo.db
├── todo.py
└── docker-compose.yml
```

Now, you can open/edit the `todo.db` file with the DBeaber.

**Comment by diman82** [comment]
@KEINOS Thanks for the elaborative answer!
I wasn't aware, that sqlite doesn't have a client-server interface.
I've already successfully tested mounting an external db.
