### ISSUE TITLE
Command history does not work

### ISSUE THREAD

**Issue by imro2** [KEINOS/Dockerfile_of_SQLite3#44]
When trying to access previous command using arrow up the shell shows control characters instead `^[[A`.

**Comment by KEINOS** [comment]
Happy new year!

> When trying to access previous command using arrow up the shell shows control characters instead `^[[A`.

That is because the default shell is [ash](https://wiki.alpinelinux.org/wiki/Change_default_shell), which does not have a "command history" functionality like `bash`.

Since this image contains the minimum to keep it lightweight, **you need to install your desired shell** in your Dockerfile.

Here's an example:

```dockerfile
FROM keinos/sqlite3:latest

USER root
RUN apk --no-cache add bash

USER sqlite
CMD /bin/bash
```

Usage:

```shellsession
$ ls
Dockerfile

$ docker build -t test .
**snip**

$ docker run --rm -it test
(inside container): /$ sqlite3 -version
(inside container): 3.44.2 2023-11-24 11:41:44 ebead0e7230cd33bcec9f95d2183069565b9e709bf745c9b5db65cc0cbf92c0f (64-bit)
(inside container): 
(inside container): /$ # now use the arrow up key to see the history
(inside container): **snip**
(inside container): 
(inside container): /$ exit
$
```
